<nav class="cssmenu">
    <ul id="lista_menu">
        <li> <a href="index.php"><span>Home</span></a></li>
        <li> <a href=""><span>Personagens</span></a>
           <ul><li><a href="Eduardo.php"><span>Eduardo</span></a> </li>
               <li><a href="Monica.php"><span>Mônica</span></a> </li>
           </ul>
        </li>
           
        <li> <a href="#">Encontro</a>
        <ul><li><a href="Encontro1.php"><span>Parte I</span></a></li>
            <li><a href="Encontro2.php"><span>Parte II</span></a></li>
            <li><a href="Encontro3.php"><span>Parte III</span></a></li>
        </ul>
        </li>
        <li> <a href="O%20Casal.php"><span>O casal</span></a></li>
        <li> <a href="Citacoes.php"><span>Citações</span></a></li>
        <li> <a href="Sobre%20a%20Musica.php"><span>Sobre a música</span></a></li>
        <li> <a href="Filme.php"><span>Filme</span></a></li>
    </ul> 
    </nav>